#!/bin/bash

kernelName="$(uname -s)"

if [ -f ".env.test" ]; then
  if [ "$kernelName" == "Darwin" ]; then
      set -a
      . .env.test
      set +a
  elif [ "$kernelName" == "Linux" ] && [ -e "/etc/lsb-release" ]; then
    source ./.env.test
  fi
fi

echo "===> Running pre-test scripts"

ts-node jest/jest.pretest.ts
